AWSTemplateFormatVersion: "2010-09-09"

Description: 'CI/CD optimized AWS CloudFormation Sample Template for AWS Service Catalog Product creation. ### Before deployment please make sure that all parameters are reviewed and updated according the specific use case. ### **WARNING** This template creates AWS Service Catalog Product, please make sure you review billing costs for AWS Service Catalog.'

Metadata:
  cfn-lint:
    config:
      regions:
        - us-east-1
        - us-west-2

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Service Catalog Product Tags
        Parameters:
          - AppName
          - Env
          - Dept
          - User
          - Owner
      - Label:
          default: Service Catalog Portfolio Stack Name
        Parameters:
          - ServiceCatalogPortfolioStackName
      - Label:
          default: Service Catalog Product Details
        Parameters:
          - SCProductName
          - SCProductDescription
          - SCProductOwner
          - SCProductSupport
          - SCProductDistributor
          - SCSupportEmail
          - SCSupportUrl
      - Label:
          default: Service Catalog Product Details
        Parameters:
          - ProvisioningArtifactTemplateUrl
          - ProvisioningArtifactNameParameter
          - ProvisioningArtifactDescriptionParameter

Parameters:

  # Enviornment type
  Env:
    Description: Please specify the target Environment. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    AllowedValues:
      - test
      - dev
      - prod
    Default: dev

  # Application Name
  AppName:
    Description: Please specify the Application Name. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    Default: app

  # Department
  Dept:
    Description: Please specify the Department. Used for tagging
    Type: String
    Default: "1234"

  # User
  User:
    Description: Please specify the User. Used for tagging
    Type: String
    Default: User

  # Owner
  Owner:
    Description: Please specify the Owner. Used for tagging
    Type: String
    Default: Owner

  # Service Catalog Portfolio Stack Name
  ServiceCatalogPortfolioStackName:
    Description: Please specify the Service Catalog Portfolio Stack Name.
    Type: String
    Default: ""

  # ServiceCatalog Product Name
  SCProductName:
    Description: Please specify ServiceCatalog Product Name.
    Type: String
    Default: ProductName

  # ServiceCatalog Product Name Description
  SCProductDescription:
    Description: Please specify ServiceCatalog Product Name Description.
    Type: String
    Default: ProductDescription

  # ServiceCatalog Product Name Owner
  SCProductOwner:
    Description: Please specify ServiceCatalog Product Owner.
    Type: String
    Default: ProductOwner

  # ServiceCatalog Product Support
  SCProductSupport:
    Description: Please specify ServiceCatalog Product Support.
    Type: String
    Default: IT Support can be reached @support

  # ServiceCatalog Product Distributor
  SCProductDistributor:
    Description: Please specify ServiceCatalog Product Distributor.
    Type: String
    Default: App Vendor

  # ServiceCatalog Product Support Email
  SCSupportEmail:
    Description: Please specify ServiceCatalog Product Support Email.
    Type: String
    Default: support@example.com

  # ServiceCatalog Product Support URL
  SCSupportUrl:
    Description: Please specify ServiceCatalog Product Support URL.
    Type: String
    Default: https://www.support.example.com

  # ServiceCatalog Product S3 Bucket
  ProvisioningArtifactTemplateUrl:
    Description: Please specify the S3 URL of the template
    Type: String
    Default: https://awsdocs.s3.amazonaws.com/servicecatalog/development-environment.template

  # ServiceCatalog Product Artifact Name
  ProvisioningArtifactNameParameter:
    Description: Please specify ServiceCatalog Product Artifact Name.
    Type: String
    Default: ProductExample

  # ServiceCatalog Product Artifact Description
  ProvisioningArtifactDescriptionParameter:
    Description: Please specify ServiceCatalog Product Artifact Description.
    Type: String
    Default: ProductExample

Resources:
  ServiceCatalogCloudFormationProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: !Ref SCProductName
      Description: !Ref SCProductDescription
      Owner: !Ref SCProductOwner
      SupportDescription: !Ref SCProductSupport
      Distributor: !Ref SCProductDistributor
      SupportEmail: !Ref SCSupportEmail
      SupportUrl: !Sub ${SCSupportUrl}
      Tags:
        - Key: Name
          Value: !Sub ${AppName}
        - Key: App
          Value: !Sub ${AppName}
        - Key: Dept
          Value: !Sub ${Dept}
        - Key: Env
          Value: !Sub ${Env}
        - Key: User
          Value: !Sub ${User}
        - Key: Owner
          Value: !Sub ${Owner}
      ProvisioningArtifactParameters:
        - Name: !Sub ${ProvisioningArtifactNameParameter}
          Description: !Sub ${ProvisioningArtifactDescriptionParameter}
          Info:
            LoadTemplateFromURL: !Sub ${ProvisioningArtifactTemplateUrl}

  ServiceCatalogPortfolioProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    DependsOn: ServiceCatalogCloudFormationProduct
    Properties:
      PortfolioId: !ImportValue
        Fn::Sub: ${ServiceCatalogPortfolioStackName}-ServiceCatalogPortfolio
      ProductId: !Ref ServiceCatalogCloudFormationProduct

  ServiceCatalogCustomTagOptionsAssociation:
    Type: AWS::ServiceCatalog::TagOptionAssociation
    Properties:
      TagOptionId: !ImportValue
        Fn::Sub: ${ServiceCatalogPortfolioStackName}-ServiceCatalogProductTagOptions
      ResourceId: !Ref ServiceCatalogCloudFormationProduct

Outputs:
  ServiceCatalogCloudFormationProductName:
    Value: !GetAtt ServiceCatalogCloudFormationProduct.ProductName
    Export:
      Name: !Sub ${AppName}-ServiceCatalogCloudFormationProductName

  ServiceCatalogProvisioningArtifactIds:
    Value: !GetAtt ServiceCatalogCloudFormationProduct.ProvisioningArtifactIds
    Export:
      Name: !Sub ${AppName}-ServiceCatalogCloudFormationProvisioningArtifactIds

  ServiceCatalogProvisioningArtifactNames:
    Value: !GetAtt ServiceCatalogCloudFormationProduct.ProvisioningArtifactNames
    Export:
      Name: !Sub ${AppName}-ServiceCatalogCloudFormationProvisioningArtifactNames
